---
kube_config_dir: "/etc/kubernetes"
kube_apiserver_port: "6443"
kube_reconfig_dir: "{{ kube_config_dir }}/reconfigure"
cm_name: "kubeadm-config"
cm_namespace: "kube-system"
kube_reconfig_file: "cm-clusterconfig-{{ now(utc=true, fmt='%Y%m%d-%H%M%S') }}.yaml"
kube_reconfig_path: "{{ kube_reconfig_dir }}/{{ kube_reconfig_file }}"
first_master_node: "groups['kube_control_plane'][0]"
