---
- name: Common tasks for every playbooks
  import_playbook: boilerplate.yml

- name: Gather facts
  import_playbook: facts.yml

- name: Tasks for reconfigure control plane
  hosts: kube_control_plane
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubernetes/control-plane, tags: master }
    - { role: kubernetes/reconfigure-control-plane, tags: ['reconfigure-control-plane'] }
